# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNYgKWRk7BSW_6WUwhirDBc40joVOgod
"""

pip install nltk numpy

import nltk
from nltk.tokenize import sent_tokenize
import textwrap  # For wrapping long lines

nltk.download('punkt')

def easy_summary(text):
    sentences = sent_tokenize(text)
    simple_points = []

    for s in sentences:
        s = s.lower()
        if "summarization" in s:
            simple_points.append("Text summarization shortens long text.")
        elif "important" in s or "main ideas" in s:
            simple_points.append("It keeps only the important meaning.")
        elif "save time" in s:
            simple_points.append("It helps people save time.")
        elif "used" in s:
            simple_points.append("It is used in news and search engines.")
        elif "types" in s or "approaches" in s:
            simple_points.append("There are two types: extractive and abstractive.")

    return simple_points

# 🔹 USER INPUT
print("Enter your text (press Enter twice to finish):")
user_text = ""
while True:
    line = input()
    if line == "":
        break
    user_text += line + " "

# 🔹 OUTPUT
print("\nEasy Summary:\n")
summary = easy_summary(user_text)

if summary:
    for line in summary:
        # Wrap lines at 50 characters
        wrapped = textwrap.fill(line, width=50)
        print(wrapped + "\n")
else:
    print("No key points found.")